### ISSUE TITLE
What is your plan for this project?

### ISSUE THREAD

**Issue by jsamr** [kazupon/api-docs-gen#22]
@kazupon Let's be honest, this project is a very promising alternative to the somehow limited api-documenter! I just want to know if it is worth the time investment. What I mean by that is that I'd love to use it in my open-source projects, and I'd be happy, beyond the reports I have already submitted, to test and send feedbacks on a regular basis. My question is, is it a hobby / prototype or do you have a reasonable confidence that it will receive frequent maintenance and dedication?

**Comment by kazupon** [comment]
Thanks for sending me some feedback! :)
I'll fix a few bugs soon!

The motivation for creating `api-docs-gen` came from the following

- Difficulty customizing the `api-documenter` markdown formatter.
  - `api-documenter` had a plugin system, but I couldn't get it to work... 
- Custom tags are not easily supported.
  - ref: https://github.com/microsoft/rushstack/issues/519

> is it a hobby / prototype or do you have a reasonable confidence that it will receive frequent maintenance and dedication?

My answer to this question is both Yes and No.

I will maintain `api-docs-gen` to the extent necessary, as it is needed in my OSS project. But if I find documenter which is more useful than `api-docs-gen`, I will switch to it from `api-docs-gen`, so I will not maintain `api-docs-gen`.

TypeScript API docs generation is something I'm interested in, so I'd like to expand on `api-docs-gen`, but I have some major OSS to work with, so I'm prioritizing that one.

**Comment by jsamr** [comment]
@kazupon Great news! Looking forwards the fixes and I'll start using it in my OSS projects too :-)
